name: openapi_generator_dart
repository: https://github.com/gibahjoe/openapi-generator-dart

packages:
  - example
  - openapi-generator
  - openapi-generator-annotations
  - openapi-generator-cli

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  coverage:
    run: dart pub global run combine_coverage --repo-path="."
