name: openapi_generator_dart

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - examples/example
  - examples/example/api/petstore_api
  - examples/openapi-generator-example
  - examples/openapi-generator-cli-example
  - packages/openapi-generator
  - packages/openapi-generator-annotations
  - packages/openapi-generator-cli

dev_dependencies:
  melos: 
